server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
  application:
    name: sunbelt

springdoc:
  swagger-ui:
    url: /open-api.yaml
openapi:
  aPIDocumentation:
    base-path: /sunbelt

